"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones, configureBoneyard } from 'boneyard-js/react'

import _dashboard_full from './dashboard-full.bones.json'
import _inventory_table from './inventory-table.bones.json'
import _products_table from './products-table.bones.json'
import _product_edit_form from './product-edit-form.bones.json'
import _transit_week_detail from './transit-week-detail.bones.json'
import _sale_detail from './sale-detail.bones.json'
import _sale_detail_modal from './sale-detail-modal.bones.json'
import _media_gallery from './media-gallery.bones.json'
import _storage_overview from './storage-overview.bones.json'
import _login_page from './login-page.bones.json'
import _pos_product_grid from './pos-product-grid.bones.json'
import _product_catalog from './product-catalog.bones.json'
import _customers_table from './customers-table.bones.json'
import _sales_table from './sales-table.bones.json'
import _export_log from './export-log.bones.json'

configureBoneyard({"color":"rgba(0,0,0,0.08)","animate":"shimmer"})

registerBones({
  "dashboard-full": _dashboard_full,
  "inventory-table": _inventory_table,
  "products-table": _products_table,
  "product-edit-form": _product_edit_form,
  "transit-week-detail": _transit_week_detail,
  "sale-detail": _sale_detail,
  "sale-detail-modal": _sale_detail_modal,
  "media-gallery": _media_gallery,
  "storage-overview": _storage_overview,
  "login-page": _login_page,
  "pos-product-grid": _pos_product_grid,
  "product-catalog": _product_catalog,
  "customers-table": _customers_table,
  "sales-table": _sales_table,
  "export-log": _export_log,
})
