"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones, configureBoneyard } from 'boneyard-js/react'

import _inventory_table from './inventory-table.bones.json'
import _dashboard_full from './dashboard-full.bones.json'
import _pos_product_grid from './pos-product-grid.bones.json'
import _product_catalog from './product-catalog.bones.json'
import _customers_table from './customers-table.bones.json'
import _sales_table from './sales-table.bones.json'
import _export_log from './export-log.bones.json'

configureBoneyard({"color":"rgba(0,0,0,0.08)","animate":"shimmer"})

registerBones({
  "inventory-table": _inventory_table,
  "dashboard-full": _dashboard_full,
  "pos-product-grid": _pos_product_grid,
  "product-catalog": _product_catalog,
  "customers-table": _customers_table,
  "sales-table": _sales_table,
  "export-log": _export_log,
})
